# Generated by Django 2.0.4 on 2018-05-17 03:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_tarea_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='fechaInicio',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
