# Generated by Django 2.0.4 on 2018-05-17 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_tarea_fechainicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='fechaInicio',
        ),
    ]
