# Generated by Django 2.0.4 on 2018-05-17 03:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_tarea_fechainicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='fechaInicio',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='%m/%d/%Y'),
            preserve_default=False,
        ),
    ]
