# Generated by Django 2.0.4 on 2018-05-20 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20180517_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='estadoTarea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.EstadoTarea'),
        ),
    ]
