# Generated by Django 2.0.4 on 2018-05-20 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20180520_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='estadoTarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.EstadoTarea'),
        ),
    ]
