# Generated by Django 2.0.4 on 2018-05-21 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20180520_1721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estadotarea',
            old_name='Estado',
            new_name='estado',
        ),
    ]
