# Generated by Django 2.0.4 on 2018-06-20 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20180521_0348'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='tipoTarea',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='main.TipoTarea'),
            preserve_default=False,
        ),
    ]
